[general]
shutdown_timeout = 2_000
rollback_timeout = 5_000

[rewrite]
enabled = false
shard_key = "ignore"
split_inserts = "error"

[[databases]]
name = "pgdog"
host = "127.0.0.1"

[admin]
password = "pgdog"
